name: Made from Concentrate
favicon: null
layout_spectrum: 0.7181029540952295
typography_spectrum: 0.4925742328632623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21609291643835604
  lightness: 0.05272096395492554
  saturation: 0.5851166229695082
  rhythmicContrast: 0.6113721255678684
purpose: []
